image: node:14.15.1

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install i -g firebase-tools
    - npm install --progress=false
    - npm run build --progress=false
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
    
deploy:
  stage: deploy
  script:
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
