build:
  stage: build
  image: node:13.7.0
  script:
  - npm install --progress=false
  - npm run build
  artifacts: 
    paths: 
    - dist/
  
deploy: 
  stage: deploy
  image: "ruby:2.5"
  script:
  # install dpl:
  - apt-get update -qy
  - apt-get install rubygems ruby-dev -y
  - gem install dpl
  # deploy to heroku:
  - dpl --provider=heroku --app=pwa-vue-js --api-key=6227efac-dd02-4db9-97e9-bf7b2488ca70 --skip_cleanup
